"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowLeft, ArrowRight, Download } from "lucide-react";
import styles from "./MemeCarousel.module.css";

const memes = [
  { id: 1, url: "https://i.em.com.br/GI_TR00H45g-1JWYvHM1ASVg9gs=/1200x1200/smart/imgsapp.em.com.br/app/noticia_127983242361/2022/11/06/1417823/meme-de-internet_1_81924.jpg", text: "O PODER DOS MEMES ESTÁ COM VOCÊ" },
  { id: 2, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvKjQTyrWUfYik63PCjUAm9X9XAW6PkpyHLw&s", text: "Intuição ou trauma???" },
  { id: 3, url: "https://i.imgflip.com/85xkix.jpg", text: "SPRINGTRAP: NO CHILDREN!?" }
];

export default function MemeCarousel() {
  const [currentIndex, setCurrentIndex] = useState(0);

  const nextMeme = () => setCurrentIndex((prev) => (prev + 1) % memes.length);
  const prevMeme = () => setCurrentIndex((prev) => (prev - 1 + memes.length) % memes.length);
  
  const downloadMeme = () => {
    const link = document.createElement("a");
    link.href = memes[currentIndex].url;
    link.download = "meme.png";
    link.click();
  };

  return (
    <div className={styles.container}>
      <div className={styles.header}>Memes generated by AI</div>
      <div className={styles.carousel}>
        <AnimatePresence>
          {memes.map((meme, index) => {
            // Define a posição correta dos memes (Stories)
            let position = "hidden";
            if (index === currentIndex) position = "center";
            else if (index === (currentIndex - 1 + memes.length) % memes.length) position = "left";
            else if (index === (currentIndex + 1) % memes.length) position = "right";

            if (position === "hidden") return null; // Oculta memes que não fazem parte do layout

            return (
              <motion.div
                key={meme.id}
                className={`${styles.meme} ${styles[position]}`}
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.9 }}
                transition={{ duration: 0.5 }}
              >
                <img src={meme.url} alt="Meme" className={styles.image} />
                <p className={styles.text}>{meme.text}</p>
              </motion.div>
            );
          })}
        </AnimatePresence>
      </div>
      <div className={styles.controls}>
        <button className={styles.button} onClick={prevMeme}><ArrowLeft /> Back</button>
        <button className={styles.download} onClick={downloadMeme}><Download /></button>
        <button className={styles.button} onClick={nextMeme}>Next <ArrowRight /></button>
      </div>
    </div>
  );
}
